export const ADD_CONSTRUCTOR_INGREDIENT = "ADD_INGRIEDIENT"
export const REMOVE_CONSTRUCTOR_INGREDIENT = "REMOVE_INGRIEDIENT"
export const UPDATE_CONSTRUCTOR_INGREDIENTS = "UPDATE_CONSTRUCTOR_INGREDIENTS"