export const ADD_CONSTRUCTOR_INGREDIENT = "ADD_INGRIEDIENT"
export const REMOVE_CONSTRUCTOR_INGREDIENT = "REMOVE_INGRIEDIENT"
export const UPDATE_CONSTRUCTOR_INGREDIENTS = "UPDATE_CONSTRUCTOR_INGREDIENTS"
export const REPLACE_CONSTRUCTOR_BUN = 'REPLACE_CONSTRUCTOR_BUN';
export const CLEAR_CONSTRUCTOR = "CLEAR_CONSTRUCTOR"